version: 2


models:
  - name: dim_date
    description: Dimension table for the date. At day granularity

    columns:
      - name: date_key
        description: The key in YYYYMMDD format as integer
        tests:
          - unique
          - not_null

      - name: DATETEIME_DAY
        description: The datetime as date

  - name: m_stations
    description: The master table for the stations.

    columns:
      - name: station_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for a station.

      - name: station_name
        description: Name of the station in string
        tests:
          - not_null

      - name: station_latitude
        description: station latitude

      - name: station_longitude
        description: station latitude

  - name: f_trips
    description: The fact table for trips

    columns:
      - name: date_key
        tests:
          - not_null

      - name: start_station_id
        tests:
          - not_null

      - name: end_station_id
        tests:
          - not_null

      - name: bikeid
      - name: usertype
      - name: birth_year
      - name: gender
      - name: tripduration
      - name: starttime
      - name: stoptime

  - name: m_weather_stations
    description: 'The master data related to wether stations located in NYC'
    columns:
      - name: station_key
        tests:
          - unique
          - not_null

      - name: name
      - name: country
      - name: region
      - name: wmo
      - name: icao
      - name: latitude
      - name: longitude
      - name: elevation
      - name: timezone

  - name: f_weather
    description: 'Fact data of the weather in NYC'
    columns:
      - name: station_key
        tests:
          - relationships:
              to: ref('m_weather_stations')
              field: station_key


      - name: date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key

      - name: obs_time
      - name: temp
      - name: dwpt
      - name: rhum
      - name: prcp
      - name: wdir
      - name: wspd
      - name: pres
      - name: coco

  - name: dim_customers
    description: 'Customers master data with SCD type 2'
    columns:
      - name: scd_id
        tests:
          - unique
          - not_null
      - name: client_id
        tests:
          - not_null
      - name: name
      - name: surname
      - name: TST_REC
      - name: VALID_FROM
      - name: VALID_TO